import './index.css'

import './methods/anchorScrollTo'
import './methods/asideHeaderHeightOnScroll'
import './methods/gsapReelSlider'
import './methods/helper'
import './methods/homeInitialAnimation'
import './methods/scrollTriggerAnimation'
import './methods/submitContactForm'
import './methods/submitNewsletterForm'
import './methods/swiperCreativeSlider'
import './methods/swiperDefaultSlider'
import './methods/toggleMenuMobile'
import './methods/toggleModal'